# Generated by Django 2.2.6 on 2019-11-11 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('imdbid', models.IntegerField()),
                ('href', models.CharField(blank=True, max_length=500, null=True)),
                ('year', models.IntegerField()),
                ('rated', models.CharField(blank=True, max_length=100, null=True)),
                ('release', models.CharField(blank=True, max_length=250, null=True)),
                ('runtime', models.CharField(blank=True, max_length=250, null=True)),
                ('write', models.CharField(blank=True, max_length=250, null=True)),
                ('actor', models.CharField(blank=True, max_length=250, null=True)),
                ('plot', models.CharField(blank=True, max_length=500, null=True)),
                ('language', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('awards', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.CharField(blank=True, max_length=250, null=True)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='asendo.Genres')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_index', models.IntegerField(blank=True, null=True)),
                ('date_watch', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='asendo.Movie')),
            ],
        ),
    ]
